### ISSUE TITLE
"babel-core" should be included in package

### ISSUE THREAD

**Issue by daenamkim** [DevExpress/testcafe-vue-selectors#51]
I got an error when using `testcafe-vue-selectors` with testcafe 1.14.0 as follows:

```sh
 Running tests in:
 - Chrome 89.0.4389.128 / macOS 11.2.3

...

ERROR Cannot prepare tests due to an error.

Error: Cannot find module 'babel-runtime/core-js/object/keys'
Require stack:
- /.../frontend/node_modules/testcafe-vue-selectors/lib/index.js
- /.../frontend/tests/login.js
- /.../frontend/node_modules/testcafe/lib/compiler/test-file/formats/es-next/compiler.js
- /.../frontend/node_modules/testcafe/lib/compiler/compilers.js
- /.../frontend/node_modules/testcafe/lib/compiler/index.js
- /.../frontend/node_modules/testcafe/lib/runner/bootstrapper.js
- /.../frontend/node_modules/testcafe/lib/runner/index.js
- /.../frontend/node_modules/testcafe/lib/testcafe.js
- /.../frontend/node_modules/testcafe/lib/index.js
- /.../frontend/node_modules/testcafe/lib/cli/cli.js
- /.../frontend/node_modules/testcafe/lib/cli/index.js
    at Object.<anonymous> (/.../frontend/node_modules/testcafe-vue-selectors/lib/index.js:5:13)
    at Object.<anonymous> (/.../frontend/tests/login.js:3:1)
```

This issue has been resolved after I installed `babel-core` as `yarn add --dev babel-core` so I think `babel-core` should be included in this package.

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe-vue-selectors/issues/51

Hi @daenamkim 

Thank you for the provided information. I've reproduced the problem.

**Comment by daenamkim** [comment]
@miherlosev Awesome!
